TestCollatz.py
FFFF..F
======================================================================
FAIL: test_eval_1 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 49, in test_eval_1
    self.assertTrue(v == 20)
AssertionError: False is not true

======================================================================
FAIL: test_eval_2 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 53, in test_eval_2
    self.assertTrue(v == 125)
AssertionError: False is not true

======================================================================
FAIL: test_eval_3 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 57, in test_eval_3
    self.assertTrue(v == 89)
AssertionError: False is not true

======================================================================
FAIL: test_eval_4 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 61, in test_eval_4
    self.assertTrue(v == 174)
AssertionError: False is not true

======================================================================
FAIL: test_solve (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./TestCollatz.py", line 80, in test_solve
    self.assertTrue(w.getvalue() == "1 10 20\n100 200 125\n201 210 89\n900 1000 174\n")
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=5)
